### ISSUE TITLE
Neuroglancer URL not valid outside neuprint

### ISSUE THREAD

**Issue by mmc46** [connectome-neuprint/neuPrintExplorer#331] opened 2022-10-14 15:04 UTC
Using the neuroglancer tab after a [query with body ids](https://neuprint.janelia.org/results?dataset=hemibrain%3Av1.2.1&qt=findneurons&q=1&qr%5B0%5D%5Bcode%5D=fn&qr%5B0%5D%5Bds%5D=hemibrain%3Av1.2.1&qr%5B0%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.2.1&qr%5B0%5D%5Bpm%5D%5Ball_segments%5D=false&qr%5B0%5D%5Bpm%5D%5Benable_contains%5D=true&qr%5B0%5D%5Bpm%5D%5Bneuron_id%5D=2138849727&qr%5B0%5D%5BvisProps%5D%5BrowsPerPage%5D=25&qr%5B1%5D%5Bcode%5D=ng&qr%5B1%5D%5Bds%5D=hemibrain%3Av1.2.1&qr%5B1%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.2.1&qr%5B1%5D%5Bpm%5D%5Bskip%5D=true&qr%5B1%5D%5Bpm%5D%5BbodyIds%5D=2138849727%2C2169538985&qr%5B2%5D%5Bcode%5D=sk&qr%5B2%5D%5Bds%5D=hemibrain%3Av1.2.1&qr%5B2%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.2.1&qr%5B2%5D%5Bpm%5D%5Bskip%5D=true&qr%5B2%5D%5Bpm%5D%5BbodyIds%5D=2138849727%2C2169538985&qr%5B2%5D%5Bpm%5D%5Bcoordinates%5D=17112.004306506584%2C33706.537610679894%2C24094.17490725145%2C17112.004306506584%2C33706.537610679894%2C31530.640225249845&qr%5B3%5D%5Bcode%5D=fn&qr%5B3%5D%5Bds%5D=hemibrain%3Av1.2.1&qr%5B3%5D%5Bpm%5D%5Bdataset%5D=hemibrain%3Av1.2.1&qr%5B3%5D%5Bpm%5D%5Ball_segments%5D=false&qr%5B3%5D%5Bpm%5D%5Benable_contains%5D=true&qr%5B3%5D%5Bpm%5D%5Bneuron_id%5D=2169538985&qr%5B3%5D%5BvisProps%5D%5BrowsPerPage%5D=25&tab=1&ftab=2) I copied the neuroglancer url using the button 'copy view URL to clipboard' so I could open it in a new tab, with just the NG  window.

[NG copied url](/#!%7B%22dimensions%22:%7B%22x%22:%5B8e-9%2C%22m%22%5D%2C%22y%22:%5B8e-9%2C%22m%22%5D%2C%22z%22:%5B8e-9%2C%22m%22%5D%7D%2C%22position%22:%5B16595%2C32209%2C32422%5D%2C%22crossSectionScale%22:1%2C%22projectionOrientation%22:%5B0.10976426303386688%2C-0.32929277420043945%2C-0.32929277420043945%2C0.8781141042709351%5D%2C%22projectionScale%22:983.7572106361007%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/emdata/clahe_yz/jpeg%22%2C%22tab%22:%22source%22%2C%22name%22:%22hemibrain:v1.2.1-grayscalejpeg%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.2/segmentation%22%2C%22tab%22:%22source%22%2C%22segments%22:%5B%222138849727%22%2C%222169538985%22%5D%2C%22name%22:%22hemibrain:v1.2.1%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%22dvid://https://hemibrain-dvid.janelia.org/3159/public_annotations?usertag=true&auth=https://hemibrain-dvid.janelia.org/api/server/token%22%2C%22tool%22:%22annotatePoint%22%2C%22tab%22:%22source%22%2C%22annotationColor%22:%22#ff0000%22%2C%22shader%22:%22#uicontrol%20vec3%20falseSplitColor%20color%28default=%5C%22#F08040%5C%22%29%5Cn#uicontrol%20vec3%20falseMergeColor%20color%28default=%5C%22#F040F0%5C%22%29%5Cn#uicontrol%20vec3%20checkedColor%20color%28default=%5C%22green%5C%22%29%5Cn#uicontrol%20vec3%20borderColor%20color%28default=%5C%22black%5C%22%29%5Cn%5Cn#uicontrol%20float%20radius%20slider%28min=3%2C%20max=20%2C%20step=1%2C%20default=10%29%5Cn#uicontrol%20float%20opacity%20slider%28min=0%2C%20max=1%2C%20step=0.1%2C%20default=1%29%20%20%5Cn%5Cnvoid%20main%28%29%20%7B%5Cn%20%20setPointMarkerSize%28radius%29%3B%5Cn%20%20float%20finalOpacity%20=%20PROJECTION_VIEW%20?%20opacity%20%2A%200.2%20:%20opacity%3B%5Cn%5Cn%20%20setPointMarkerBorderColor%28vec4%28borderColor%2C%20finalOpacity%29%29%3B%5Cn%20%20if%20%28prop_rendering_attribute%28%29%20==%201%29%20%7B%5Cn%20%20%20%20setColor%28vec4%28checkedColor%2C%20finalOpacity%29%29%3B%5Cn%20%20%7D%20else%20if%20%28prop_rendering_attribute%28%29%20==%202%29%20%7B%20%20%20%20%5Cn%20%20%20%20setColor%28vec4%28falseSplitColor%2C%20finalOpacity%29%29%3B%5Cn%20%20%7D%20else%20if%20%28prop_rendering_attribute%28%29%20==%203%29%20%20%7B%5Cn%20%20%20%20setColor%28vec4%28falseMergeColor%2C%20finalOpacity%29%29%3B%5Cn%20%20%7D%20else%20%7B%5Cn%20setColor%28vec4%281%2C%200%2C%200%2C%20finalOpacity%29%29%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22name%22:%22hemibrain:v1.2.1-public_annotations%22%7D%2C%7B%22type%22:%22annotation%22%2C%22source%22:%22precomputed://gs://neuroglancer-janelia-flyem-hemibrain/v1.2/synapses%22%2C%22tab%22:%22source%22%2C%22shader%22:%22#uicontrol%20vec3%20preColor%20color%28default=%5C%22yellow%5C%22%29%5Cn#uicontrol%20vec3%20postColor%20color%28default=%5C%22gray%5C%22%29%5Cn#uicontrol%20float%20preConfidence%20slider%28min=0%2C%20max=1%2C%20default=0%29%5Cn#uicontrol%20float%20postConfidence%20slider%28min=0%2C%20max=1%2C%20default=0%29%5Cn#uicontrol%20float%20sliceViewOpacity%20slider%28min=0%2C%20max=1%2C%20default=0.5%29%5Cn#uicontrol%20float%20projectionViewOpacity%20slider%28min=0%2C%20max=1%2C%20default=0.3%29%5Cn%5Cnvoid%20main%28%29%20%7B%5Cn%20%20float%20opacity%20=%20PROJECTION_VIEW%20?%20projectionViewOpacity%20:%20sliceViewOpacity%3B%5Cn%20%20setColor%28vec4%28defaultColor%28%29%2C%20opacity%29%29%3B%5Cn%20%20setEndpointMarkerColor%28%5Cn%20%20%20%20vec4%28preColor%2C%20opacity%29%2C%5Cn%20%20%20%20vec4%28postColor%2C%20opacity%29%29%3B%5Cn%20%20setEndpointMarkerBorderColor%28%5Cn%20%20%20%20vec4%280%2C%200%2C%200%2C%20opacity%29%2C%5Cn%20%20%20%20vec4%280%2C%200%2C%200%2C%20%20%20%20%20opacity%29%5Cn%20%20%29%3B%5Cn%5Cn%20%20setEndpointMarkerSize%285.0%2C%205.0%29%3B%5Cn%20%20setLineWidth%282.0%29%3B%5Cn%20%20if%20%28prop_pre_synaptic_confidence%28%29%3C%20preConfidence%20%7C%7C%5Cn%20%20prop_post_synaptic_confidence%28%29%3C%20postConfidence%29%20discard%3B%5Cn%7D%5Cn%22%2C%22linkedSegmentationLayer%22:%7B%22pre_synaptic_cell%22:%22hemibrain:v1.2.1%22%2C%22post_synaptic_cell%22:%22hemibrain:v1.2.1%22%7D%2C%22filterBySegmentation%22:%5B%22post_synaptic_cell%22%2C%22pre_synaptic_cell%22%5D%2C%22name%22:%22hemibrain:v1.2.1-synapses%22%7D%5D%2C%22layout%22:%22xy-3d%22%7D)

It doesn't generate a valid url however. 

Is this intended behaviour or a bug?

**Comment by stuarteberg** [comment] 2022-11-09 18:48
duplicate of #325

**Closed by stuarteberg** 2022-11-09 18:48 UTC
